import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { json, apiError } from "@/lib/http";
import { requireParent, requireOwnedChild, withGuard } from "@/lib/guard";
import { rateLimit } from "@/lib/ratelimit";
import { decrypt } from "@/lib/crypto";
import { summarizeWeekWithLLM } from "@/lib/openrouter";
import { buildChildReport } from "@/lib/report";
import { RISK_CATEGORY_LABELS } from "@/lib/risk";

type Ctx = { params: Promise<{ childId: string }> };

const ALERT_LABELS: Record<string, string> = {
  blocked_attempt: "tentatives bloquées",
  new_app: "nouvelles apps",
  limit_reached: "limites atteintes",
  geofence: "zones",
  keyword: "mots-clés sensibles",
  risk: "risques détectés",
  panic: "SOS",
  device_offline: "appareil hors-ligne",
  time_request: "demandes de temps",
};

const mins = (seconds: number) => Math.round(seconds / 60);

// POST /api/children/:id/ai-summary — a warm weekly summary generated by the
// parent's own LLM from AGGREGATE stats only (no private message content).
export async function POST(_req: NextRequest, ctx: Ctx) {
  return withGuard(async () => {
    const parent = await requireParent();
    const { childId } = await ctx.params;
    const child = await requireOwnedChild(parent.id, childId);

    const cfg = await prisma.parent.findUnique({
      where: { id: parent.id },
      select: { aiEnabled: true, aiModel: true, aiApiKey: true },
    });
    if (!cfg?.aiEnabled || !cfg.aiApiKey || !cfg.aiModel) {
      return apiError("Activez d'abord l'IA (clé OpenRouter + modèle) dans les Réglages.", 400);
    }

    // On-demand + spends the parent's quota → throttle.
    const rl = rateLimit(`aisummary:${parent.id}`, 20, 60 * 60_000);
    if (!rl.ok) {
      return Response.json({ error: "Trop de résumés générés. Réessayez plus tard." }, { status: 429, headers: { "Retry-After": String(rl.retryAfter) } });
    }

    const report = await buildChildReport(childId, 7, child.tzOffsetMinutes);
    const data = {
      enfant: child.name,
      periode: "7 derniers jours",
      tempsEcran: { totalMin: mins(report.totalSeconds), moyenneParJourMin: mins(report.avgPerDaySeconds) },
      topApps: report.topApps.slice(0, 5).map((a) => ({ app: a.appName, minutes: mins(a.seconds) })),
      topCategories: report.byCategory.slice(0, 5).map((c) => ({ categorie: c.category, minutes: mins(c.seconds) })),
      web: { visites: report.web.totalVisits, bloquees: report.web.blockedVisits },
      alertes: {
        total: report.alerts.total,
        parType: report.alerts.byType.map((b) => ({ type: ALERT_LABELS[b.type] ?? b.type, nombre: b.count })),
      },
      categoriesRisque: Object.values(RISK_CATEGORY_LABELS),
    };

    const summary = await summarizeWeekWithLLM(decrypt(cfg.aiApiKey), cfg.aiModel, data);
    if (!summary) return apiError("Le modèle n'a pas pu générer le résumé. Réessayez.", 502);
    return json({ summary });
  });
}
