import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { json, apiError } from "@/lib/http";
import { requireParent, requireOwnedChild, withGuard } from "@/lib/guard";
import { rateLimit } from "@/lib/ratelimit";
import { tryDecrypt } from "@/lib/crypto";
import { summarizeWeekWithLLM } from "@/lib/openrouter";
import { buildChildReport } from "@/lib/report";
import { buildAiSummaryInput } from "@/lib/ai-summary-input";

type Ctx = { params: Promise<{ childId: string }> };

// POST /api/children/:id/ai-summary — a warm weekly summary generated by the
// parent's own LLM from AGGREGATE stats only (no private message content).
export async function POST(_req: NextRequest, ctx: Ctx) {
  return withGuard(async () => {
    const parent = await requireParent();
    const { childId } = await ctx.params;
    const child = await requireOwnedChild(parent.id, childId);

    const cfg = await prisma.parent.findUnique({
      where: { id: parent.id },
      select: { aiEnabled: true, aiModel: true, aiApiKey: true },
    });
    if (!cfg?.aiEnabled || !cfg.aiApiKey || !cfg.aiModel) {
      return apiError("Activez d'abord l'IA (clé OpenRouter + modèle) dans les Réglages.", 400);
    }

    // On-demand + spends the parent's quota → throttle.
    const rl = await rateLimit(`aisummary:${parent.id}`, 20, 60 * 60_000);
    if (!rl.ok) {
      return Response.json({ error: "Trop de résumés générés. Réessayez plus tard." }, { status: 429, headers: { "Retry-After": String(rl.retryAfter) } });
    }

    const report = await buildChildReport(childId, 7, child.tzOffsetMinutes);
    const data = buildAiSummaryInput(child.name, report, 7);

    // Fail-closed: a key that no longer decrypts (DATA_ENC_KEY rotated) must
    // surface as an actionable error, not go to OpenRouter as ciphertext.
    const apiKey = tryDecrypt(cfg.aiApiKey);
    if (!apiKey) return apiError("Clé OpenRouter illisible (clé de chiffrement changée ?). Re-saisissez votre clé dans les Réglages.", 503);

    const summary = await summarizeWeekWithLLM(apiKey, cfg.aiModel, data);
    if (!summary) return apiError("Le modèle n'a pas pu générer le résumé. Réessayez.", 502);
    return json({ summary });
  });
}
